version: "3.5"

services:
  mysql-db:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=bayztrackerdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - spring-boot-mysql

  spring-boot-app:
    image: spring-boot-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/bayztrackerdb?allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=user
      - spring.datasource.password=pass
      - spring.jpa.hibernate.ddl-auto=create
    depends_on:
      - mysql-db
    networks:
      - spring-boot-mysql

networks:
  spring-boot-mysql: